### Prueba 1: Registro con errores (Debe devolver 400 Validation Error)
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "correo-invalido",
  "password": "123"
}

###

### Prueba 2: Registro con éxito (Debe devolver 200 OK y limpiar campos extra)
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "TEST@USUARIO.COM",
  "password": "Password123",
  "campo_hacker": "esto_deberia_desaparecer"
}

### Prueba 3: Login Correcto (Debe devolver el Token)
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "TEST@USUARIO.COM",
  "password": "Password123"
}

### Prueba 4: Acceso denegado (Sin Token)
GET http://localhost:3000/api/user/me

###

### Prueba 5: Acceso permitido (Con Token)
# Importante: Copia el token que te dio el Login y pégalo después de "Bearer"
GET http://localhost:3000/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmRkNWMyODljMTViZGJmMzM3Y2M3MyIsImlhdCI6MTc3NDA1MDY0OCwiZXhwIjoxNzc0MTM3MDQ4fQ._MbTnMqgpifHXozG2qndTcW02o1caD7vCRuRUKBeMe4